name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./runTests.py test/unit/math/prim --make-only
    - name: build
      run: ./runTests.py test/unit/math/prim
